### ISSUE TITLE
problems with installation cl-containers 

### ISSUE THREAD

**Issue by bach741974** [akovalenko/sbcl-win32-threads#7] opened 2011-07-29 12:06 UTC
I have problems with the installation of cl-containers package when trying to use this fork through quicklisp or asdf (sbcl-1.0.50.1., 1.0.50, and others).

There are no problems with ccl 1.6 or original sbcl 1.0.50.

Some part of log is 

Error while trying to load definition for system cl-containers
from pathname
C:/Documents and Settings/bahvalov.ROCKET1/quicklisp/dists/quicklisp/software/cl-containers-20110320-git/cl-containers.asd:

   couldn't resolve C:\Documents and Settings\bahvalov.ROCKET1\Application Data\common-lisp\cache\sbcl-1.0.50.1.mswinmt.866-0ebae5b-win-x86\C\Documents and Settings\bahvalov.ROCKET1\quicklisp\dists\quicklisp\software\asdf-system-connections-20101006-darcs\dev\ASDF-TMP-asdf-system-connections.fasl:
     No such file or directory
   [Condition of type ASDF:LOAD-SYSTEM-DEFINITION-ERROR]

Restarts:
 0: [TRY-RECOMPILING] Try recompiling asdf-system-connections
 1: [RETRY] Retry compiling #<CL-SOURCE-FILE "asdf-system-connections" "dev" "asdf-system-connections">.
 2: [ACCEPT] Continue, treating compiling #<CL-SOURCE-FILE "asdf-system-connections" "dev" "asdf-system-connections"> as having been successful.
 3: [RETRY] Retry EVAL of current toplevel form.
 4: [CONTINUE] Ignore error and continue loading file "C:\Documents and Settings\bahvalov.ROCKET1\quickli...".
 5: [ABORT] Abort loading file "C:\Documents and Settings\bahvalov.ROCKET1\quickli...".
 --more--

Backtrace:
  0: ((FLET #:LAMBDA3370) #<SB-INT:SIMPLE-FILE-ERROR "~@<~?: ~2I~_~A~:>" {24C10E79}>)
  1: (SIGNAL #<SB-INT:SIMPLE-FILE-ERROR "~@<~?: ~2I~_~A~:>" {24C10E79}>)
  2: (ERROR ..)
  3: (SB-IMPL::SIMPLE-FILE-PERROR ..)
  4: ((FLET SB-IMPL::FAIL) ..)
  5: (SB-IMPL::QUERY-FILE-SYSTEM ..)
  6: (SB-IMPL::QUERY-FILE-SYSTEM ..)[:EXTERNAL]
  7: (TRUENAME ..)
  8: (RENAME-FILE ..)
  9: (ASDF:COMPILE-FILE\* ..)
 10: ((SB-PCL::FAST-METHOD ASDF:PERFORM (ASDF:COMPILE-OP ASDF:CL-SOURCE-FILE)) ..)
 11: ((SB-PCL::EMF ASDF:PERFORM) #<unused argument> #<unused argument> #<ASDF:COMPILE-OP NIL {248DF269}> #<ASDF:CL-SOURCE-FILE "asdf-system-connections" "dev" "asdf-system-connections">)
 12: ((SB-PCL::FAST-METHOD ASDF::PERFORM-WITH-RESTARTS (ASDF:COMPILE-OP ASDF:CL-SOURCE-FILE)) ..)
 13: ((LAMBDA ()))
 14: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK))
 15: ((FLET #:WITHOUT-INTERRUPTS-BODY-[CALL-WITH-RECURSIVE-LOCK]329))
 16: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK) {22E195}> #<SB-THREAD:MUTEX "World Lock" owner: #<SB-THREAD:THREAD "initial thread" RUNNING {23CE8669}>>)
 17: ((FLET SB-C::WITH-IT))
 18: ((SB-PCL::FAST-METHOD ASDF::PERFORM-PLAN (LIST)) ..)
 19: ((SB-PCL::EMF ASDF::PERFORM-PLAN) ..)
 --more--

and 

CL-USER> (asdf:load-system  :cl-containers)
; compiling file "C:/Documents and Settings/bahvalov.ROCKET1/quicklisp/dists/quicklisp/software/asdf-system-connections-20101006-darcs/dev/asdf-system-connections.lisp" (written 29 JUL 2011 04:26:20 PM):
; compiling (IN-PACKAGE #:ASDF)
; compiling (EXPORT (QUOTE #))
; compiling (DEFCLASS SYSTEM-CONNECTION ...)
; compiling (DEFUN MAP-SYSTEM-CONNECTIONS ...)
; compiling (DEFMACRO DEFSYSTEM-CONNECTION ...)
; compiling (DEFUN LOAD-CONNECTED-SYSTEMS ...)
; compiling (DEFUN REQUIRED-SYSTEMS-LOADED-P ...)
; compiling (DEFUN SYSTEM-LOADED-P ...)
; compiling (DEFMETHOD PERFORM ...)
; compiling (DEFMETHOD OPERATION-DONE-P ...)
; compiling (DEFUN FIND-SYSTEM-IN-MEMORY ...)
; compiling (PUSHNEW :ASDF-SYSTEM-CONNECTIONS ...)

; C:/Documents and Settings/bahvalov.ROCKET1/Application Data/common-lisp/cache/sbcl-1.0.50.1.mswinmt.866-0ebae5b-win-x86/C/Documents and Settings/bahvalov.ROCKET1/quicklisp/dists/quicklisp/software/asdf-system-connections-20101006-darcs/dev/ASDF-TMP-asdf-system-connections.fasl written
; compilation finished in 0:00:00.141

**Comment by akovalenko** [comment] 2011-07-29 22:35
The problem is caused by native pathname being longer than MAX_PATH-1 (259) characters. Such pathnames don't work well with original SBCL/windows too; the only difference here is that my (lisp-implementation-version) is longer.

Though I'm going to fix this MAX_PATH limitation (it's possible by using only Unicode filesystem API everywhere), I've heard more than once that having such long pathnames on Windows is not a good idea (some tools, like CMD.EXE builtins, may have MAX_PATH restriction as well). I'd recommend to set up ASDF output translations so resulting pathnames are shorter.

You may want to try my stand-alone executables: they use ACLREPL with a few aliases defined to work with Quicklisp, and if quicklisp is not loaded by your .sbclrc, they download quicklisp and set up output translations for shorter output names (within quicklisp hierarchy). The only command, `:qload cl-containers`, should result in quicklisp setup + cl-containers compiled and loaded. (Unfortunately, if quicklisp is auto-loaded in your .sbclrc, this installation will be reused, so the problem with long filenames will remain).

**Comment by bach741974** [comment] 2011-07-31 15:28
Thank you very much for the answer.

**Comment by bach741974** [comment] 2011-08-02 05:14
I have changed the output translations as you advise. It works. Thanks.

**Comment by akovalenko** [comment] 2011-08-09 01:00
BTW, I'm facing a grim dilemma with this issue: it turns out not to be so hard to add support for file names longer than MAX_PATH, yet there is a huge reason for users not to be thankful for it.

So far, I've tried long file names on Windows XP, and neither CMD.EXE nor the standard "shell" GUI could do anything sensible with such a file once it's created. To make things uglier, there is no sensible error indication -- CMD.EXE just assures me there is no such file (though it get listed by DIR); GUI shell is unable to rename, move or delete it, and here we have complete silence instead of an error message: the file just stays where it was created, no matter how I try to drag-drop, or shift-del, etc. (I didn't try this on a newer OS, so maybe it's fixed on modern Windows -- I hope for it). 

I finally managed to delete such a file using CMD.EXE, when I remembered that 8.3 short file names are still there (and DIR /X shows them).

Now I have to decide if it's any good for SBCL to manipulate such filenames (and, especially, create them). Given that MAX_PATH limit is so easily overstepped, it may be better to fail right when it happens.

I'm going to take a look at newer OSes before deciding (and let's keep this issue open for now). Any comments and arguments from you-the-original-reporter or any other smart people will be appreciated.

**Comment by akovalenko** [comment] 2011-08-18 09:16
Long pathnames shouldn't be a problem for SBCL anymore; they work for me without visible flaws since commit 48728e69d8d128ede9f6. The new binaries I've uploaded recently should work too, for all combinations of x86, x64 and .exe, .msi.
Caution: OS Windows will be less happy than SBCL with this kind of file names -- see the previous comment for details.

It would be interesting to hear independent confirmations (or refutations) of my SBCL's success with full path names longer than 260 characters (btw, pathname _components_ still shouldn't reach that length -- component length seems to have a hard limit that is even lower).

**Closed as completed** 2012-01-27 07:20 UTC
